job:
  time_limit: 96h0m0s
  flavor: h100-1x
  region: ix-m5-sm11
  image: python:3.10
  generate_name: train_task_1
  work_dir: /work
  env:
    access_key_id: 
    secret_access_key: 
    train_patch: data/pred_appeal/grocery_model/main_model/
    train_masks_task: data/pred_appeal/grocery_model/main_model/

  args:
    - sh
    - -c
    - |
      pip3 install -qr requirements.txt &&\
      python3 --version &&\
      python3 train.py

  input:
    - type: files
      src: ./
      dst: "/work/"
      mask: "requirements.txt"

    - type: files
      src: ./
      dst: "/work/"
      mask: "*.py"

