job:
  time_limit: 96h0m0s
  flavor: h100-1x
  region: ix-m5-sm11
  image: python:3.10
  generate_name: train_task_1
  work_dir: /work

  args:
    - sh
    - -c
    - |
      pip3 install -qr requirements.txt &&\
      python3 --version &&\
      python3 train.py

  input:
    - type: files
      src: ./
      dst: "/work/"
      mask: "requirements.txt"

    - type: files
      src: ./
      dst: "/work/"
      mask: "*.py"

    - type: s3msk          
      src: data/3_efdl/task_1/CARVANA
      bucket: rnd-customer-service-platform-ml-data
      dst: "/work/"
      access_key: 0091f8778e77f116cf7e
      secret_key: Q0P4a0Uf1T+zHN4is+i9fuPh4H6rbWEix6srEZ+V


